#!/bin/bash

# .NET Auto Builder

echo "put this batch file in ur project folder"
echo "and also copy the important part of my .csproj file to ur .csproj file before i can proceed"
echo "press any key to start compile"
read -n 1 -s

cd "$(dirname "$(realpath "$0")")" || exit 1

echo
echo "deleting old bin + obj..."
if [ -d bin ]; then rm -rf bin; fi
if [ -d obj ]; then rm -rf obj; fi

echo
echo "restoring project..."
dotnet restore -r win-x64

if [ $? -ne 0 ]; then
    echo "restore failed :c"
    read -r
    exit 1
fi

echo
echo "building release singlefile..."
dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true

if [ $? -ne 0 ]; then
    echo "build failed :c"
    read -r
    exit 1
fi

echo
echo "F I N I S H E D"
echo "output should be in:"
echo "bin/Release/net6.0/win-x64/publish/"
read -n 1 -s
